name: Deploy the lambda function

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Libraries
        run: |
          cd lambda
          python -m pip install --upgrade pip
          if [-f requirements.txt]; then pip install -r requirements.txt -t .; fi
      - name: Create Bundle
        run: |
          cd lambda
          zip -r ../${{ github.sha }}.zip .
      - name: Archive Bundle Into Artifact
        uses: actions/upload-artifact@v3
        with:
          name: zip-bundle-lambda
          path: ${{ github.sha }}.zip

  upload:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: zip-bundle-lambda
      - name: Configure Credentials - AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
      - name: Upload Artifact to S3
        run: aws s3 cp ${{ github.sha }}.zip s3://github-actions-deploy-lambda/${{ github.repository }}/${{ github.sha }}.zip

  deploy:
    runs-on: ubuntu-20.04
    needs: upload
    steps:
      - name: Configure Credentials - AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
      - name: Update Lambda Function Code
        run: |
          aws lambda update-function-code \
          --function-name github-actions \
          --s3-bucket github-actions-deploy-lambda \
          --s3-key ${{ github.sha }}.zip \
          --publish
